# Generated by Django 5.2.4 on 2025-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.BooleanField(default=True),
        ),
    ]
