# Generated by Django 5.2.4 on 2025-08-02 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('petitioner', models.CharField(max_length=100)),
                ('respondent', models.CharField(max_length=100)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('order_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case_type', models.CharField(max_length=40)),
                ('case_number', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('raw_html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('pdf_url', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='case_search.casedata')),
            ],
        ),
        migrations.AddField(
            model_name='casedata',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_search.querylog'),
        ),
    ]
