# Generated by Django 5.2.4 on 2025-08-02 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querylog',
            old_name='timestamp',
            new_name='searched_at',
        ),
        migrations.RemoveField(
            model_name='casedata',
            name='order_link',
        ),
        migrations.RemoveField(
            model_name='casedata',
            name='query',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='raw_html',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='success',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='year',
        ),
        migrations.AddField(
            model_name='casedata',
            name='case_number',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casedata',
            name='cnr',
            field=models.CharField(default='Unkown', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querylog',
            name='cnr_number',
            field=models.CharField(default='Unknown', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casedata',
            name='court_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casedata',
            name='filing_date',
            field=models.CharField(default=datetime.date(2025, 8, 2), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casedata',
            name='hearing_date',
            field=models.CharField(default=datetime.date(2025, 1, 1), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casedata',
            name='petitioner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casedata',
            name='registration_date',
            field=models.CharField(default=datetime.date(2025, 1, 1), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casedata',
            name='respondent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='casedata',
            name='status',
            field=models.CharField(default='Unkown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(default=datetime.date(2025, 1, 1), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='summary',
            field=models.TextField(default='Not Available'),
            preserve_default=False,
        ),
    ]
