# Generated by Django 5.2.4 on 2025-08-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_search', '0002_rename_timestamp_querylog_searched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='cnr_number',
            field=models.CharField(max_length=30),
        ),
    ]
