# Generated by Django 5.2.1 on 2025-05-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_complete_task_completed_remove_task_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1),
        ),
    ]
