# Generated by Django 5.2.2 on 2025-07-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='hex_code',
        ),
    ]
