# Generated by Django 5.2.1 on 2025-07-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartitem_color_alter_productsize_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
